Repository UMC-Replendar/Server, pull requests merged in 2025-02, with the labels that each got.

#49 :sparkles: Feat [#48] 사용자 상태 메시지 설정, 회원 정보 조회 api 작성
  src/main/java/Umc/replendar/user/controller/UserController.java
  src/main/java/Umc/replendar/user/dto/res/UserDtoRes.java
  src/main/java/Umc/replendar/user/service/UserService.java
Labels: :sparkles: feature

#50 ✨🔨 Feat Ref [#48] 사용자 api 작성/수정
  src/main/java/Umc/replendar/global/util/AmazonS3Util.java
  src/main/java/Umc/replendar/user/controller/S3Controller.java
  src/main/java/Umc/replendar/user/controller/TestS3Controller.java
  src/main/java/Umc/replendar/user/controller/UserController.java
  src/main/java/Umc/replendar/user/dto/req/UserDtoReq.java
  src/main/java/Umc/replendar/user/dto/res/UserDtoRes.java
  src/main/java/Umc/replendar/user/entity/School.java
  src/main/java/Umc/replendar/user/entity/User.java
  src/main/java/Umc/replendar/user/repository/SchoolRepository.java
  src/main/java/Umc/replendar/user/repository/UserRepository.java
  src/main/java/Umc/replendar/user/service/UserService.java
Labels: :sparkles: feature, 🔨 Refactor

#51 ✨ [#38] 히스토리, 조회 로그 - 과제 공유 수락, 로그 - 과제 공유 거절 api 작성
  src/main/java/Umc/replendar/activitylog/controller/ActivityController.java
  src/main/java/Umc/replendar/activitylog/converter/logConverter.java
  src/main/java/Umc/replendar/activitylog/dto/req/ActivityLogReq.java
  src/main/java/Umc/replendar/activitylog/dto/res/ActivityLogRes.java
  src/main/java/Umc/replendar/activitylog/dto/res/LogTypeRes.java
  src/main/java/Umc/replendar/activitylog/dto/res/TypeId.java
  src/main/java/Umc/replendar/activitylog/entity/Action.java
  src/main/java/Umc/replendar/activitylog/entity/ActivityLog.java
  src/main/java/Umc/replendar/activitylog/repository/ActivityLogRepository.java
  src/main/java/Umc/replendar/activitylog/repository/ActivityRepository.java
  src/main/java/Umc/replendar/activitylog/service/ActivityService.java
  src/main/java/Umc/replendar/activitylog/service/ActivityServiceImpl.java
  src/main/java/Umc/replendar/assignment/converter/AssToDto.java
  src/main/java/Umc/replendar/assignment/dto/resDto/AssignmentRes.java
  src/main/java/Umc/replendar/assignment/entity/AssNotifyCycle.java
  src/main/java/Umc/replendar/assignment/entity/NotifyLog.java
  src/main/java/Umc/replendar/assignment/repository/NotifyLogRepository.java
  src/main/java/Umc/replendar/assignment/service/AssignmentServiceImpl.java
  src/main/java/Umc/replendar/friend/repository/FriendRequestRepository.java
  src/main/java/Umc/replendar/user/entity/User.java
Labels: :sparkles: feature

#53 ✨ [#38] 과제 활동 로그 및 알림 로그 읽음 처리 API 작성 완료
  src/main/java/Umc/replendar/activitylog/controller/ActivityController.java
  src/main/java/Umc/replendar/activitylog/service/ActivityService.java
  src/main/java/Umc/replendar/activitylog/service/ActivityServiceImpl.java
  src/main/java/Umc/replendar/user/entity/User.java
  src/main/java/Umc/replendar/user/service/UserService.java
Labels: :sparkles: feature

#57 🌎 deploy [#38] 로그 controller 수정
  src/main/java/Umc/replendar/activitylog/controller/ActivityController.java
Labels: :earth_asia: Depoly

#58 :sparkles: Feat [#48] 회원 탈퇴 api 작성
  src/main/java/Umc/replendar/user/controller/UserController.java
  src/main/java/Umc/replendar/user/service/UserService.java
Labels: :sparkles: feature

#59 ✨ [#38] 배포시 에러 수정
  src/main/java/Umc/replendar/activitylog/controller/ActivityController.java
  src/main/java/Umc/replendar/activitylog/service/ActivityService.java
  src/main/java/Umc/replendar/activitylog/service/ActivityServiceImpl.java
  src/main/java/Umc/replendar/user/entity/User.java
Labels: :earth_asia: Depoly

#60 🌍 deploy [#38, #48] 회원탈퇴 api 및 배포시 controller 에러 수정
  src/main/java/Umc/replendar/activitylog/controller/ActivityController.java
  src/main/java/Umc/replendar/activitylog/service/ActivityService.java
  src/main/java/Umc/replendar/activitylog/service/ActivityServiceImpl.java
  src/main/java/Umc/replendar/user/controller/UserController.java
  src/main/java/Umc/replendar/user/entity/User.java
  src/main/java/Umc/replendar/user/service/UserService.java
Labels: :sparkles: feature, :earth_asia: Depoly

#64 ✨ [#63] 내정보 조회 API 작성
  src/main/java/Umc/replendar/assignment/entity/Assignment.java
  src/main/java/Umc/replendar/assignment/repository/AssignmentRepository.java
  src/main/java/Umc/replendar/user/controller/UserController.java
  src/main/java/Umc/replendar/user/dto/res/UserDtoRes.java
  src/main/java/Umc/replendar/user/service/UserService.java
Labels: :sparkles: feature

#70 :sparkles: Feat [#69] 친구 캘린더 조회 API 작성
  src/main/java/Umc/replendar/assignment/controller/AssignmentController.java
  src/main/java/Umc/replendar/assignment/repository/AssignmentRepository.java
  src/main/java/Umc/replendar/assignment/service/AssignmentService.java
  src/main/java/Umc/replendar/assignment/service/AssignmentServiceImpl.java
Labels: :sparkles: feature

#71 :hammer: Ref [#48] 프로필 이미지 변경 API 수정
  src/main/java/Umc/replendar/global/util/AmazonS3Util.java
Labels: :bug: bug

#72 :hammer: Ref [#23] 친구 조회 API 수정
  src/main/java/Umc/replendar/friend/dto/resDto/FriendRes.java
  src/main/java/Umc/replendar/friend/service/FriendGroupServiceImpl.java
  src/main/java/Umc/replendar/user/controller/S3Controller.java
Labels: 🔨 Refactor

#73 🌍 [DEPLOY] #23, #48, #69 배포
  src/main/java/Umc/replendar/activitylog/dto/res/ActivityLogRes.java
  src/main/java/Umc/replendar/activitylog/service/ActivityServiceImpl.java
  src/main/java/Umc/replendar/assignment/controller/AssignmentController.java
  src/main/java/Umc/replendar/assignment/dto/reqDto/AssignmentReq.java
  src/main/java/Umc/replendar/assignment/entity/Assignment.java
  src/main/java/Umc/replendar/assignment/repository/AssignmentRepository.java
  src/main/java/Umc/replendar/assignment/service/AssignmentService.java
  src/main/java/Umc/replendar/assignment/service/AssignmentServiceImpl.java
  src/main/java/Umc/replendar/friend/dto/resDto/FriendRes.java
  src/main/java/Umc/replendar/friend/service/FriendGroupServiceImpl.java
  src/main/java/Umc/replendar/global/util/AmazonS3Util.java
  src/main/java/Umc/replendar/user/controller/S3Controller.java
Labels: :earth_asia: Depoly

#76 :hammer: Ref [#75] 과제 공유할 친구 조회 res 수정
  src/main/java/Umc/replendar/assignment/converter/AssToDto.java
  src/main/java/Umc/replendar/assignment/dto/resDto/AssignmentRes.java
Labels: 🔨 Refactor

#79 🌍 Depoly [#75] 모든 친구 조회 res, api 수정 배포
  src/main/java/Umc/replendar/assignment/converter/AssToDto.java
  src/main/java/Umc/replendar/assignment/dto/resDto/AssignmentRes.java
  src/main/java/Umc/replendar/friend/converter/FriToDto.java
  src/main/java/Umc/replendar/friend/service/FriendGroupServiceImpl.java
  src/main/java/Umc/replendar/friend/service/FriendServiceImpl.java
Labels: :earth_asia: Depoly

#82 Refactor/#75
  src/main/java/Umc/replendar/assignment/controller/AssignmentController.java
  src/main/java/Umc/replendar/friend/converter/FriToDto.java
  src/main/java/Umc/replendar/friend/entity/friendship.java
  src/main/java/Umc/replendar/friend/service/FriendGroupServiceImpl.java
  src/main/java/Umc/replendar/friend/service/FriendServiceImpl.java
Labels: 🔨 Refactor

#83 🌏 Deploy [#75] 배포
  src/main/java/Umc/replendar/assignment/controller/AssignmentController.java
  src/main/java/Umc/replendar/friend/converter/FriToDto.java
  src/main/java/Umc/replendar/friend/entity/friendship.java
  src/main/java/Umc/replendar/friend/service/FriendGroupServiceImpl.java
  src/main/java/Umc/replendar/friend/service/FriendServiceImpl.java
Labels: :earth_asia: Depoly

#84 🔨 Ref [#75] 친구 api 수정
  src/main/java/Umc/replendar/assignment/controller/AssignmentController.java
  src/main/java/Umc/replendar/assignment/service/AssignmentService.java
  src/main/java/Umc/replendar/assignment/service/AssignmentServiceImpl.java
  src/main/java/Umc/replendar/friend/controller/FriendGroupController.java
  src/main/java/Umc/replendar/friend/converter/FriToDto.java
  src/main/java/Umc/replendar/friend/dto/resDto/FriendRes.java
  src/main/java/Umc/replendar/friend/service/FriendGroupService.java
  src/main/java/Umc/replendar/friend/service/FriendGroupServiceImpl.java
Labels: 🔨 Refactor

#85 🌏 Depoly [#75] 배포
  src/main/java/Umc/replendar/assignment/controller/AssignmentController.java
  src/main/java/Umc/replendar/assignment/service/AssignmentService.java
  src/main/java/Umc/replendar/assignment/service/AssignmentServiceImpl.java
  src/main/java/Umc/replendar/friend/controller/FriendGroupController.java
  src/main/java/Umc/replendar/friend/converter/FriToDto.java
  src/main/java/Umc/replendar/friend/dto/resDto/FriendRes.java
  src/main/java/Umc/replendar/friend/service/FriendGroupService.java
  src/main/java/Umc/replendar/friend/service/FriendGroupServiceImpl.java
Labels: :earth_asia: Depoly

#88 🌏 Deploy [#75] 배포
  src/main/java/Umc/replendar/user/entity/User.java
Labels: :earth_asia: Depoly

#90 🌏 Deploy [#75] 배포
  src/main/java/Umc/replendar/user/entity/User.java
Labels: :earth_asia: Depoly

#92 🌏 Deploy [#75] 배포
  src/main/java/Umc/replendar/user/entity/User.java
Labels: :earth_asia: Depoly

#93 :hammer: Ref [#75] 회원 탈퇴 api 수정 진짜 마지막..
  src/main/java/Umc/replendar/user/entity/User.java
Labels: 🔨 Refactor

#94 🌏 Deploy [#75] 배포
  src/main/java/Umc/replendar/user/entity/User.java
Labels: :earth_asia: Depoly

#95 [FEAT] 과제목록 API 작성
  src/main/java/Umc/replendar/activitylog/controller/ActivityController.java
  src/main/java/Umc/replendar/activitylog/dto/res/ActivityLogRes.java
  src/main/java/Umc/replendar/activitylog/service/ActivityService.java
  src/main/java/Umc/replendar/activitylog/service/ActivityServiceImpl.java
  src/main/java/Umc/replendar/major/controller/majorController.java
  src/main/java/Umc/replendar/major/converter/MajorConverter.java
  src/main/java/Umc/replendar/major/dto/req/LectureReq.java
  src/main/java/Umc/replendar/major/dto/res/LectureAssignmentRes.java
  src/main/java/Umc/replendar/major/repository/LectureAssignmentRepository.java
  src/main/java/Umc/replendar/major/service/MajorService.java
  src/main/java/Umc/replendar/major/service/MajorServiceImpl.java
Labels: :sparkles: feature

#96 🌎 [#66] 배포
  src/main/java/Umc/replendar/activitylog/controller/ActivityController.java
  src/main/java/Umc/replendar/activitylog/dto/res/ActivityLogRes.java
  src/main/java/Umc/replendar/activitylog/service/ActivityService.java
  src/main/java/Umc/replendar/activitylog/service/ActivityServiceImpl.java
  src/main/java/Umc/replendar/major/controller/majorController.java
  src/main/java/Umc/replendar/major/converter/MajorConverter.java
  src/main/java/Umc/replendar/major/dto/req/LectureReq.java
  src/main/java/Umc/replendar/major/dto/res/LectureAssignmentRes.java
  src/main/java/Umc/replendar/major/repository/LectureAssignmentRepository.java
  src/main/java/Umc/replendar/major/service/MajorService.java
  src/main/java/Umc/replendar/major/service/MajorServiceImpl.java
Labels: :earth_asia: Depoly

#97 :hammer: Ref [#75] 친구 소식 api 리팩터링
  src/main/java/Umc/replendar/activitylog/converter/logConverter.java
  src/main/java/Umc/replendar/activitylog/dto/res/ActivityLogRes.java
  src/main/java/Umc/replendar/activitylog/service/ActivityServiceImpl.java
Labels: 🔨 Refactor

#98 🌏 Deploy [#75] 배포
  src/main/java/Umc/replendar/activitylog/converter/logConverter.java
  src/main/java/Umc/replendar/activitylog/dto/res/ActivityLogRes.java
  src/main/java/Umc/replendar/activitylog/service/ActivityServiceImpl.java
Labels: :earth_asia: Depoly

#99 Feature/66
  src/main/java/Umc/replendar/major/controller/majorController.java
  src/main/java/Umc/replendar/major/converter/MajorConverter.java
  src/main/java/Umc/replendar/major/dto/res/MajorRes.java
  src/main/java/Umc/replendar/major/repository/MajorRepository.java
  src/main/java/Umc/replendar/major/service/MajorService.java
  src/main/java/Umc/replendar/major/service/MajorServiceImpl.java
Labels: :sparkles: feature, 🔨 Refactor

#100 🌎 Deploy [#66] 배포
  src/main/java/Umc/replendar/major/controller/majorController.java
  src/main/java/Umc/replendar/major/converter/MajorConverter.java
  src/main/java/Umc/replendar/major/dto/res/MajorRes.java
  src/main/java/Umc/replendar/major/repository/MajorRepository.java
  src/main/java/Umc/replendar/major/service/MajorService.java
  src/main/java/Umc/replendar/major/service/MajorServiceImpl.java
Labels: :earth_asia: Depoly

#101 :hammer: Ref [#75] 친구 목록 조회 api 수정 (프로필 사진 url 나오도록)
  src/main/java/Umc/replendar/friend/converter/FriToDto.java
  src/main/java/Umc/replendar/friend/dto/resDto/FriendRes.java
  src/main/java/Umc/replendar/friend/service/FriendGroupServiceImpl.java
  src/main/java/Umc/replendar/friend/service/FriendServiceImpl.java
Labels: 🔨 Refactor

#102 🌏 Deploy [#75] 배포
  src/main/java/Umc/replendar/friend/converter/FriToDto.java
  src/main/java/Umc/replendar/friend/dto/resDto/FriendRes.java
  src/main/java/Umc/replendar/friend/service/FriendGroupServiceImpl.java
  src/main/java/Umc/replendar/friend/service/FriendServiceImpl.java
Labels: :earth_asia: Depoly

#103 :hammer: Ref [#75] 친구 목록 조회 api 수정 (친구 프로필 사진 url 나오도록)
  src/main/java/Umc/replendar/friend/service/FriendServiceImpl.java
Labels: 🔨 Refactor

#104 🌏 Deploy [#75] 배포
  src/main/java/Umc/replendar/friend/service/FriendServiceImpl.java
Labels: :earth_asia: Depoly

#105 🔨 Ref [#75] 친구 요청 api 수정
  src/main/java/Umc/replendar/activitylog/controller/ActivityController.java
  src/main/java/Umc/replendar/activitylog/converter/logConverter.java
  src/main/java/Umc/replendar/activitylog/dto/res/ActivityLogRes.java
  src/main/java/Umc/replendar/activitylog/service/ActivityService.java
  src/main/java/Umc/replendar/activitylog/service/ActivityServiceImpl.java
Labels: 🔨 Refactor

#106 🌏 Deploy [#75] 배포
  src/main/java/Umc/replendar/activitylog/controller/ActivityController.java
  src/main/java/Umc/replendar/activitylog/converter/logConverter.java
  src/main/java/Umc/replendar/activitylog/dto/res/ActivityLogRes.java
  src/main/java/Umc/replendar/activitylog/service/ActivityService.java
  src/main/java/Umc/replendar/activitylog/service/ActivityServiceImpl.java
Labels: :earth_asia: Depoly

#108 :hammer: Ref [#75] 과제 조회 (완료, 중요 과제)api 수정
  src/main/java/Umc/replendar/activitylog/dto/res/ActivityLogRes.java
  src/main/java/Umc/replendar/assignment/converter/AssToDto.java
  src/main/java/Umc/replendar/assignment/dto/resDto/AssignmentRes.java
  src/main/java/Umc/replendar/global/function/TaskTimer.java
Labels: 🔨 Refactor

#109 🌏 Deploy [#75] 배포
  src/main/java/Umc/replendar/activitylog/dto/res/ActivityLogRes.java
  src/main/java/Umc/replendar/assignment/converter/AssToDto.java
  src/main/java/Umc/replendar/assignment/dto/resDto/AssignmentRes.java
  src/main/java/Umc/replendar/global/function/TaskTimer.java
Labels: :earth_asia: Depoly

#110 :hammer: Ref [#75] 과제 조회 (완료, 중요 과제)api 수정
  src/main/java/Umc/replendar/assignment/converter/AssToDto.java
  src/main/java/Umc/replendar/assignment/dto/resDto/AssignmentRes.java
Labels: :earth_asia: Depoly

#111 🌏 Deploy [#75] 배포
  src/main/java/Umc/replendar/assignment/converter/AssToDto.java
  src/main/java/Umc/replendar/assignment/dto/resDto/AssignmentRes.java
Labels: :earth_asia: Depoly

#113 :hammer: Refactor [#112] 히스토리 API 수정
  src/main/java/Umc/replendar/activitylog/repository/ActivityLogRepository.java
  src/main/java/Umc/replendar/activitylog/service/ActivityServiceImpl.java
  src/main/java/Umc/replendar/assignment/repository/NotifyLogRepository.java
  src/main/java/Umc/replendar/friend/repository/FriendRequestRepository.java
Labels: 🔨 Refactor

#114 🌎 Deploy [#112] 배포
  src/main/java/Umc/replendar/activitylog/repository/ActivityLogRepository.java
  src/main/java/Umc/replendar/activitylog/service/ActivityServiceImpl.java
  src/main/java/Umc/replendar/assignment/repository/NotifyLogRepository.java
  src/main/java/Umc/replendar/friend/repository/FriendRequestRepository.java
Labels: 🔨 Refactor, :earth_asia: Depoly

#115 :sparkles: Feat [#107] 특정 강의의 과제 목록 조회 API 작성
  src/main/java/Umc/replendar/major/controller/LectureAssignmentController.java
  src/main/java/Umc/replendar/major/converter/MajorConverter.java
  src/main/java/Umc/replendar/major/service/LectureAssignmentService.java
  src/main/java/Umc/replendar/major/service/LectureAssignmentServiceImpl.java
Labels: :sparkles: feature

#116 🌏 Deploy [#107] 배포
  src/main/java/Umc/replendar/major/controller/LectureAssignmentController.java
  src/main/java/Umc/replendar/major/converter/MajorConverter.java
  src/main/java/Umc/replendar/major/service/LectureAssignmentService.java
  src/main/java/Umc/replendar/major/service/LectureAssignmentServiceImpl.java
Labels: :earth_asia: Depoly

#119 :sparkles: FEAT [#118] 단일 친구에게 과제 공유 API 작성
  src/main/java/Umc/replendar/assignment/entity/Assignment.java
  src/main/java/Umc/replendar/assignment/repository/AssignmentRepository.java
  src/main/java/Umc/replendar/assignment/repository/ShareRepository.java
  src/main/java/Umc/replendar/friend/controller/FriendController.java
  src/main/java/Umc/replendar/friend/dto/reqDto/FriendReq.java
  src/main/java/Umc/replendar/friend/dto/resDto/FriendRes.java
  src/main/java/Umc/replendar/friend/service/FriendService.java
  src/main/java/Umc/replendar/friend/service/FriendServiceImpl.java
Labels: :sparkles: feature

#122 🌎 DEPLOY 리다이렉트 uri 수정
  src/main/resources/application-deploy.yml
Labels: :earth_asia: Depoly

#124 :sparkles: Feat [#117] 방명록 작성, 조회 API 작성
  src/main/java/Umc/replendar/major/service/LectureAssignmentServiceImpl.java
  src/main/java/Umc/replendar/user/controller/GuestBookController.java
  src/main/java/Umc/replendar/user/converter/GuestBookConverter.java
  src/main/java/Umc/replendar/user/dto/req/GuestBookDtoReq.java
  src/main/java/Umc/replendar/user/dto/res/GuestBookDtoRes.java
  src/main/java/Umc/replendar/user/entity/GuestBook.java
  src/main/java/Umc/replendar/user/entity/User.java
  src/main/java/Umc/replendar/user/repository/GuestBookRepository.java
  src/main/java/Umc/replendar/user/service/GuestBookService.java
Labels: :sparkles: feature

#125 🌏 Deploy [#117] 방명록 api 배포
  src/main/java/Umc/replendar/major/service/LectureAssignmentServiceImpl.java
  src/main/java/Umc/replendar/user/controller/GuestBookController.java
  src/main/java/Umc/replendar/user/converter/GuestBookConverter.java
  src/main/java/Umc/replendar/user/dto/req/GuestBookDtoReq.java
  src/main/java/Umc/replendar/user/dto/res/GuestBookDtoRes.java
  src/main/java/Umc/replendar/user/entity/GuestBook.java
  src/main/java/Umc/replendar/user/entity/User.java
  src/main/java/Umc/replendar/user/repository/GuestBookRepository.java
  src/main/java/Umc/replendar/user/service/GuestBookService.java
Labels: :earth_asia: Depoly

#127 🌎 Deploy [#123] 배포
  src/main/java/Umc/replendar/ReplendarApplication.java
  src/main/java/Umc/replendar/assignment/controller/AssignmentController.java
  src/main/java/Umc/replendar/assignment/converter/AssToDto.java
  src/main/java/Umc/replendar/assignment/dto/resDto/AssignmentRes.java
  src/main/java/Umc/replendar/assignment/entity/AssNotifyCycle.java
  src/main/java/Umc/replendar/assignment/repository/AssNotifyCycleRepository.java
  src/main/java/Umc/replendar/assignment/service/AssignmentService.java
  src/main/java/Umc/replendar/assignment/service/AssignmentServiceImpl.java
  src/main/java/Umc/replendar/common/ScheduleService.java
  src/main/java/Umc/replendar/major/entity/LectureAssignment.java
  src/main/java/Umc/replendar/major/repository/LectureRepository.java
  src/main/java/Umc/replendar/major/repository/UserLectureAssignmentRepository.java
  src/main/java/Umc/replendar/major/service/MajorServiceImpl.java
  src/main/java/Umc/replendar/user/entity/AcademicYear.java
Labels: :earth_asia: Depoly

#128 :sparkles: Feat [#123] 과제 알림 로그 API 수정 , 카카오 리다이렉트 코드 수정
  src/main/java/Umc/replendar/activitylog/controller/ActivityController.java
  src/main/java/Umc/replendar/activitylog/converter/logConverter.java
  src/main/java/Umc/replendar/activitylog/dto/res/ActivityLogRes.java
  src/main/java/Umc/replendar/user/service/KakaoService.java
Labels: :sparkles: feature

#129 🌍 DEPLOY [#123] 배포
  src/main/java/Umc/replendar/activitylog/controller/ActivityController.java
  src/main/java/Umc/replendar/activitylog/converter/logConverter.java
  src/main/java/Umc/replendar/activitylog/dto/res/ActivityLogRes.java
  src/main/java/Umc/replendar/user/service/KakaoService.java
Labels: :earth_asia: Depoly

#130 :hammer: Refactor 과제 삭제 및 수정 예외처리
  README.md
  src/main/java/Umc/replendar/assignment/controller/AssignmentController.java
  src/main/java/Umc/replendar/assignment/service/AssignmentService.java
  src/main/java/Umc/replendar/assignment/service/AssignmentServiceImpl.java
Labels: :sparkles: feature
